version: '3'

volumes:
  static:
  database:
  redis_data:

services:
  mysite:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: mysite
    container_name: mysite
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh
    depends_on:
      - redis

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: mysite_nginx
    container_name: mysite_nginx
    volumes:
      - static:/apps/mysite/static
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: 'bitnami/redis:5.0'
    container_name: mysite_redis
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    env_file:
      - .envs/.production
